#!/usr/bin/env bash
#
#   \|/  ||     /|| |\/|| ||''.
#  - o - ||    /-|| |  || ||--'
#   /|\  ||_| /  || |  || ||
#
# Description: A simple script that makes the focused terminal look brighter
# Dependencies: art, wmctrl, xdpyinfo
# Author: gawlk

# ---
# VARS
# ---
colors="${HOME}/.colors"

gry=$(grep "gry" "$colors" | awk '{ print $3 }')
red=$(grep "red" "$colors" | awk '{ print $3 }')
grn=$(grep "grn" "$colors" | awk '{ print $3 }')
blu=$(grep "blu" "$colors" | awk '{ print $3 }')
wht=$(grep "wht" "$colors" | awk '{ print $3 }')

ctheme=$(cat ${HOME}/.colors | head -2 | tail -1 | cut -d" " -f2)

val=32

# ---
# CONVERTERS
# ---

hex_to_rgb() {
    # Each part of the color in [0-255]
    R=$(( 16#${1:1:2} ))
    G=$(( 16#${1:3:2} ))
    B=$(( 16#${1:5:2} ))
}

rgb_to_hex() {
    hex=$(printf "#%02X%02X%02X" "$R" "$G" "$B")
    echo "${hex,,}"
}

# ---
# SEQUENCES
# ---

set_special() {
    sequences+="\033]${1};${2}\007"
}

set_color() {
    sequences+="\033]4;${1};${2}\007"
}

set_sequences() {
    sequences=

    # spe
    set_special 10  "$wht"
    set_special 12  "$wht"
    set_special 13  "$wht"

    # gry
    set_color 8  "$gry"
    
    # red
    set_color 1  "$red"
    set_color 5  "$red"
    set_color 9  "$red"
    set_color 13 "$red"
    
    # grn
    set_color 2  "$grn"
    set_color 3  "$grn"
    set_color 10 "$grn"
    set_color 11 "$grn"
    
    # blu
    set_color 4  "$blu"
    set_color 6  "$blu"
    set_color 12 "$blu"
    set_color 14 "$blu"

    # wht
    set_color 7  "$wht"
    set_color 15 "$wht"
}

# ---
# UNFOCUSED
# ---

unfocus_color() {
    hex_to_rgb "$1"
    
    [[ "$ctheme" == "dark" ]] && val=$(( - val ))
   
    (( R += val ))
    (( G += val ))
    (( B += val ))
    
    [[ $R -lt 0 ]] && R=0
    [[ $G -lt 0 ]] && G=0
    [[ $B -lt 0 ]] && B=0
    [[ $R -gt 255 ]] && R=255
    [[ $G -gt 255 ]] && G=255
    [[ $B -gt 255 ]] && B=255

    rgb_to_hex
}

update_unfocused() {
    for term in /dev/pts/[0-9]*
    do  
        [[ -w "$term" ]] && [[ "$term" != "$focused" ]] && printf "%b" "$sequences" > "$term" &
    done
}

# ---
# MAIN
# ---

main() {
    # Get id of the focused window
    id=$(xdpyinfo | grep -Eo 'window 0x[^,]+' | cut -d" " -f2 | cut -c 3-)

    # Check if the focused window is a terminal
    focused=$(wmctrl -l | grep "${id}.*/dev/pts/" | awk '{ print $4 }')

    # If it is a terminal
    if [[ -n "$focused" ]]
    then
        # Set normal colors to it
        set_sequences
        printf "%b" "$sequences" > "$focused" &

        # Generate unfosed colors
        gry=$(unfocus_color "$gry")
        red=$(unfocus_color "$red")
        grn=$(unfocus_color "$grn")
        blu=$(unfocus_color "$blu")
        (( val *= 2 ))
        wht=$(unfocus_color "$wht")
        
        # Update unfocused terminals
        set_sequences
        update_unfocused
    fi
}

main
